- name: configuring webserver and deploying index.html file
hosts: webserver
become: yes
tasks: 
  - name: ensure apache2 server installed
    apt:
      name: httpd
      state: present
      update_cache: yes
  - namae: deploying custom index.html
    copy:
      content: "welcome to our site"
      dest: /var/www/html/index.html
      mode: 0644
      notify: restart apache
  - name: start the httpd service
    service: 
      name: httpd
      state: started
      enabled: yes

handlers:
  - name: restart apache2
    service: 
      name: httpd
      state: restarted
    
